import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';

import Header from './components/MainHeader';
import Footer from './components/MainFooter';

import { Main } from 'next/document';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <a href="/favicon.ico" rel="icon" />
      </Head>

      <body className="bg-purple-200">{children}</body>
    </html>
  );
}
